### ISSUE TITLE
Missing service for homebridge-config-ui-x

### ISSUE THREAD

**Issue by Kentzo** [kubiko/homebridge-snap#2]
Please consider adding the homebridge-config-ui-x as a service, disabled by default.

**Comment by kubiko** [comment]
Hi @Kentzo 
Sorry for late reply. I have been busy with other projects so I did not have time to do a proper refactor.
I have now refactored snap, it's using `homebridge-config-ui-x`  and I removed previous `homebridge-info` and `homebridge-server` plugins which were trying to do the same but not in as polished way.
I have completely refactored snap otherwise, so it is now ~20% smaller to install and it should also consume less space when installed as `homebridge`, `homebridge-config-ui-x`, `npm` and `node` are now run directly from snap, only additionally installed plugins go to `SNAP_COMMON`. So actual install size should be also about ~200MB smaller. It assumes that snap has the latest version for those. Which is a fair assumption given it's built almost daily.
I also changed the versioning scheme, now it's homebridge version + build date.
This is currently in the edge. channel, while I'm testing it and I will move it to stable once validated.

Snap is now base core22, so it should be using the latest packages from Ubuntu 22.04 LTS release.

Let me please know if this works for you.

**Comment by Kentzo** [comment]
I have recently updated and was glad to find that nothing broke :)

However, my specific request  was not addressed: I'm looking for a snap-friendly shortcut to enable / disable the UI plugin.

Currently I have to edit homebridge's config and have to restart manually.

**Comment by kubiko** [comment]
@Kentzo not sure if I follow.
If by "UI plugin" you refer to `homebridge-config-ui-x` plugin, then there is an easy way to control it on snap level, since `homebridge-config-ui-x` runs as a separate service, you do
to disable: `snap stop --disable homebridge.homebridge-config-ui-x`
to enable: `snap start --enable homebridge.homebridge-config-ui-x`
once disabled if you want to only start it in one-off: `snap start homebridge.homebridge-config-ui-x`

**Comment by Kentzo** [comment]
I do not see the `homebridge-config-ui-x` service:

```
$ snap services
Service                Startup  Current  Notes
homebridge.homebridge  enabled  active   -

$ snap list | grep homebridge
homebridge  1.6.0-2022-12-09  3009   latest/stable  ondra        -
```

**Comment by kubiko** [comment]
hmm, I was wrong it's separate binary but not running as own service.
So in this case you really have to manage it through config file I'm afraid.
not ideal.
Not sure what would be the idea option here.
possibly `snap set homebridge <>=on` / `snap set homebridge <>=off`
but that would require some wiring that config hook would edit config in place and that can go easily wrong... What config option do you use to enable/disable it?

**Comment by Kentzo** [comment]
I edit /var/snap/homebridge/common/config.json. IIRC the plugin is ON be default so to turn it off I add the following:

```javascript
{
    ...
    "disabledPlugins": [
        "homebridge-config-ui-x"
    ],
    ...
}
```
